/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code401challenges;

import org.junit.Test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class BinarySearchTest {
    @Test public void testBinarySearch_EvenArray_Happy() {
        int[] testArr = {4,8,15,16,23,42};
        int target = 15;

        assertTrue("BinarySearch with target should return 'true' because it includes the target", BinarySearch.binarySearch(testArr, target) == 2 );
    }

    @Test public void testBinarySearch_EvenArray_Sad() {
        int[] testArr = {11,22,33,44,55,66,77};
        int target = 90;

        assertTrue("BinarySearch without target should return 'true' because it does not includes the target", BinarySearch.binarySearch(testArr, target) == -1 );
    }


}
