/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant {
    private String name;
    private int stars;
    private String price;
    private ArrayList<Review> reviews = new ArrayList<>();

//    constructor
    Restaurant(String name, int stars, String price) {
        this.name = name;
        this.stars = stars;
        this.price = price;
    }

    public void addReview(String body, String author, int stars, Restaurant restaurant){

        reviews.add(new Review(body, author, stars, this));
        int sum = 0;
        for (Review review : this.reviews){
            sum += review.getStars();
        }
        this.setStars(sum / this.reviews.size());
    }

    public ArrayList<Review> getReviews() {
        return this.reviews;
    }

    public void setStars(int stars) {
        this.stars = stars;
    }

    public String getName(){
        return this.name;
    }

    public int getStars(){
        return this.stars;
    }

    public String getPrice(){
        return this.price;
    }

    @Override
    public String toString(){
        return String.format("%s is a %d star restaurant that costs %s", this.getName(), this.getStars(), this.getPrice());
    }



}
