/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testlintErGates() {
        App.lintEr("src/main/resources/gates.js");
    }

    @Test public void testlintErEmpty() {
        App.lintEr("src/main/resources/empty.js");
    }

    @Test public void testlintErFewErrors() {
        App.lintEr("src/main/resources/fewErrors.js");
    }

    @Test public void testlintErNoErrors() {
        App.lintEr("src/main/resources/noErrors.js");
    }

    @Test public void testlintErOneError() {
        App.lintEr("src/main/resources/oneError.js");
    }
}
