/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testlintErGates() {
        assertEquals(App.lintEr("src/main/resources/gates.js"), 46); ;
    }

    @Test public void testlintErEmpty() {
        assertEquals(App.lintEr("src/main/resources/empty.js"), 0);
    }

    @Test public void testlintErFewErrors() {
        assertEquals(App.lintEr("src/main/resources/fewErrors.js"), 2);
    }

    @Test public void testlintErNoErrors() {
        assertEquals(App.lintEr("src/main/resources/noErrors.js"), 0);
    }

    @Test public void testlintErOneError() {
        assertEquals(App.lintEr("src/main/resources/oneError.js"), 1);
    }
}
