/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FilterReader;
import java.util.Scanner;

public class App {

    public static String lintEr(String path) {
        Scanner s = null;
        try {
            s = new Scanner(new BufferedReader(new FileReader(path)));
            int line = 0;
            while (s.hasNextLine()){
                line++;
                String readMe = s.nextLine();
                if (!readMe.endsWith(";") && readMe.length()>0 && !(readMe.endsWith("{") || readMe.endsWith("}") || readMe.contains("if") || readMe.contains("else"))){
                    System.out.println("Line " + line + ": Missing semicolon.");
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        return "Hello world.";
    }

    public static void main(String[] args) {
        lintEr("src/main/resources/gates.js");

    }
}
