/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FilterReader;
import java.util.Scanner;

public class App {

    public static int lintEr(String path) {
        Scanner s = null;
        int line = 0;
        int ErrorCount = 0;
        try {
            s = new Scanner(new BufferedReader(new FileReader(path)));

            while (s.hasNextLine()){
                line++;
                String readMe = s.nextLine();
//                readMe.matches(".[{};]$")... ish
                if (readMe.length()>0 && !(readMe.endsWith(";") || readMe.endsWith("{") || readMe.endsWith("}") || readMe.contains("if") || readMe.contains("else"))){
                    ErrorCount++;
                    System.out.println("Line " + line + ": Missing semicolon.");
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        System.out.println("Line " + ErrorCount);
        return ErrorCount;
    }

    public static void main(String[] args) {
        lintEr("src/main/resources/gates.js");

    }
}
